// Mocks generated by Mockito 5.4.4 from annotations
// in mobile/test/features/jobs/create_job_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i8;
import 'dart:ui' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mobile/features/auth/providers/auth_provider.dart' as _i4;
import 'package:mobile/shared/models/models.dart' as _i3;
import 'package:mobile/shared/services/api_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJob_2 extends _i1.SmartFake implements _i3.Job {
  _FakeJob_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i4.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadUser() => (super.noSuchMethod(
        Invocation.method(
          #loadUser,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> register(
    String? email,
    String? password,
    String? name,
    String? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            name,
            role,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i7.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i5.Future<_i3.User> register(
    String? email,
    String? password,
    String? name,
    String? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            name,
            role,
          ],
        ),
        returnValue: _i5.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #register,
            [
              email,
              password,
              name,
              role,
            ],
          ),
        )),
      ) as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.User> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.User>);

  @override
  _i5.Future<String> uploadPhoto(_i8.File? file) => (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [file],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadPhoto,
            [file],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<Map<String, double>> geocodeZip(String? zip) =>
      (super.noSuchMethod(
        Invocation.method(
          #geocodeZip,
          [zip],
        ),
        returnValue: _i5.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<List<_i3.Job>> getJobs() => (super.noSuchMethod(
        Invocation.method(
          #getJobs,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Job>>.value(<_i3.Job>[]),
      ) as _i5.Future<List<_i3.Job>>);

  @override
  _i5.Future<_i3.Job> createJob({
    required String? title,
    required String? description,
    required double? price,
    required double? latitude,
    required double? longitude,
    required int? posterId,
    required List<_i8.File>? photos,
    String? zipCode,
    String? category,
    List<String>? tags,
    bool? isUrgent = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createJob,
          [],
          {
            #title: title,
            #description: description,
            #price: price,
            #latitude: latitude,
            #longitude: longitude,
            #posterId: posterId,
            #photos: photos,
            #zipCode: zipCode,
            #category: category,
            #tags: tags,
            #isUrgent: isUrgent,
          },
        ),
        returnValue: _i5.Future<_i3.Job>.value(_FakeJob_2(
          this,
          Invocation.method(
            #createJob,
            [],
            {
              #title: title,
              #description: description,
              #price: price,
              #latitude: latitude,
              #longitude: longitude,
              #posterId: posterId,
              #photos: photos,
              #zipCode: zipCode,
              #category: category,
              #tags: tags,
              #isUrgent: isUrgent,
            },
          ),
        )),
      ) as _i5.Future<_i3.Job>);

  @override
  _i5.Future<void> updateJobStatus(
    int? jobId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJobStatus,
          [
            jobId,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createReview(
    int? jobId,
    int? revieweeId,
    int? rating,
    String? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReview,
          [
            jobId,
            revieweeId,
            rating,
            comment,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Review>> getUserReviews(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserReviews,
          [userId],
        ),
        returnValue: _i5.Future<List<_i3.Review>>.value(<_i3.Review>[]),
      ) as _i5.Future<List<_i3.Review>>);

  @override
  _i5.Future<void> toggleSaveJob(int? jobId) => (super.noSuchMethod(
        Invocation.method(
          #toggleSaveJob,
          [jobId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<int>> getSavedJobIds() => (super.noSuchMethod(
        Invocation.method(
          #getSavedJobIds,
          [],
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);

  @override
  _i5.Future<List<_i3.AppNotification>> getNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
        ),
        returnValue: _i5.Future<List<_i3.AppNotification>>.value(
            <_i3.AppNotification>[]),
      ) as _i5.Future<List<_i3.AppNotification>>);

  @override
  _i5.Future<void> markNotificationRead(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markNotificationRead,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> applyForJob(
    int? jobId,
    int? doerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyForJob,
          [
            jobId,
            doerId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> createPaymentIntent(
    int? jobId,
    double? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPaymentIntent,
          [
            jobId,
            amount,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i3.Conversation>> getConversations(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversations,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i3.Conversation>>.value(<_i3.Conversation>[]),
      ) as _i5.Future<List<_i3.Conversation>>);

  @override
  _i5.Future<List<_i3.Message>> getMessages(
    int? userId,
    int? otherUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [
            userId,
            otherUserId,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Message>>.value(<_i3.Message>[]),
      ) as _i5.Future<List<_i3.Message>>);
}
